# -*- coding: utf-8 -*-
"""Student Performance Analysis System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13dpLZ7sYdr1gYVXXSHKehdXG0qX3s7vS

Import Libraries
"""

import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns

"""Generate Synthetic Data"""

np.random.seed(42)

n = 250

names = [f"Student_{i}" for i in range(1, n+1)]
genders = np.random.choice(['Male', 'Female'], n)
departments = np.random.choice(['CSE', 'IT', 'ECE'], n)
years = np.random.choice(['1st', '2nd', '3rd'], n)
maths = np.random.randint(35, 100, n)
science = np.random.randint(35, 100, n)
english = np.random.randint(35, 100, n)
attendance = np.random.randint(50, 101, n)
internal = np.random.randint(5, 26, n)

df = pd.DataFrame({
    'Student_ID': range(1, n+1),
    'Name': names,
    'Gender': genders,
    'Department': departments,
    'Year': years,
    'Maths': maths,
    'Science': science,
    'English': english,
    'Attendance (%)': attendance,
    'Internal Marks': internal
})

"""Feature Engineering"""

df['Total'] = df['Maths'] + df['Science'] + df['English']
df['Average'] = df['Total'] / 3

"""Grade Classification"""

def grade(avg):
    if avg >= 90:
        return 'A'
    elif avg >= 75:
        return 'B'
    elif avg >= 60:
        return 'C'
    else:
        return 'Fail'

df['Grade'] = df['Average'].apply(grade)

"""Save Dataset"""

df.to_csv("student_performance.csv", index=False)

print("Dataset Created Successfully!\n")
print(df.head())

""" Basic EDA"""

print("\nSummary Statistics:\n")
print(df.describe())

top_students = df.sort_values(by='Average', ascending=False).head(10)
print("\nTop 10 Students:\n", top_students[['Name', 'Average']])

low_students = df[df['Grade'] == 'Fail']
print("\nFail Students:\n", low_students[['Name', 'Average']])

"""Group Analysis"""

print("\nDepartment-wise Performance:\n", df.groupby('Department')['Average'].mean())

print("\nGender-wise Performance:\n", df.groupby('Gender')['Average'].mean())

print("\nYear-wise Performance:\n", df.groupby('Year')['Average'].mean())

"""Visualization

Bar Chart-Department
"""

df.groupby('Department')['Average'].mean().plot(kind='bar', title="Department Performance")
plt.ylabel("Average Marks")
plt.show()

"""Pie Chart-Gender"""

df['Gender'].value_counts().plot(kind='pie', autopct='%1.1f%%', title="Gender Distribution")
plt.show()

"""Histogram-Average Marks"""

plt.hist(df['Average'], bins=10)
plt.title("Marks Distribution")
plt.xlabel("Average Marks")
plt.ylabel("Count")
plt.show()

""" Scatter-Attendance vs Average"""

plt.scatter(df['Attendance (%)'], df['Average'])
plt.title("Attendance vs Marks")
plt.xlabel("Attendance")
plt.ylabel("Average Marks")
plt.show()

"""Scatter-Internal vs Average"""

plt.scatter(df['Internal Marks'], df['Average'])
plt.title("Internal Marks vs Performance")
plt.xlabel("Internal Marks")
plt.ylabel("Average Marks")
plt.show()

